# Generated by Django 4.0.5 on 2023-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_data', models.TextField(verbose_name='Medical Data')),
                ('check_up_doctor', models.CharField(max_length=50, verbose_name='Doctor Appointed')),
                ('date_of_checkup', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffsAndDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, verbose_name='UserName')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('role', models.CharField(max_length=50, verbose_name='Role')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
    ]
