# Generated by Django 4.0.5 on 2023-02-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDetails',
            fields=[
                ('general_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='UserName')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('role', models.CharField(default='user', max_length=50, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(max_length=500, verbose_name='Address')),
                ('marital', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, verbose_name='Marital Status')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, verbose_name='Gender')),
                ('religion', models.CharField(max_length=25, verbose_name='Religion')),
                ('caste', models.CharField(max_length=50, verbose_name='Caste')),
                ('phone', models.BigIntegerField(verbose_name='Phone number')),
                ('bloodgroup', models.CharField(choices=[('O positive', 'O positive'), ('A positive', 'A positive'), ('B positive', 'B positive'), ('AB positive', 'AB positive'), ('O negative', 'O negative'), ('A negative', 'A negative'), ('B negative', 'B negative'), ('AB negative', 'AB negative')], max_length=50, verbose_name='Blood Group')),
                ('general_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.generaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hospital Name')),
                ('phone', models.BigIntegerField(verbose_name='Phone number')),
                ('doctors', models.TextField(verbose_name='Doctors')),
                ('staffs', models.TextField(verbose_name='Staffs')),
                ('general_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.generaldetails')),
            ],
        ),
    ]
