# Generated by Django 4.0.5 on 2023-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='staffs',
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='role',
            field=models.CharField(max_length=50, verbose_name='role'),
        ),
    ]
