# Generated by Django 4.0.5 on 2023-02-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_remove_hospital_doctors_remove_hospital_staffs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='general_id',
            new_name='general_details',
        ),
    ]
